from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
import io
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

def create_ecg_plot(signal, title="ECG Waveform"):
    """Create a matplotlib plot of the ECG signal and return it as a BytesIO buffer."""
    plt.figure(figsize=(8, 3))
    plt.plot(signal, color='#ef4444', linewidth=1.5)
    plt.grid(True, linestyle='--', alpha=0.3)
    plt.title(title, fontsize=10)
    plt.xlabel('Time (samples)', fontsize=8)
    plt.ylabel('Amplitude', fontsize=8)
    plt.tight_layout()
    
    buf = io.BytesIO()
    plt.savefig(buf, format='png', dpi=150)
    plt.close()
    buf.seek(0)
    return buf

def generate_pdf_report(data):
    """
    Generate a PDF medical report for ECG analysis.
    Expected data dict:
    - signal: list of floats
    - beat_type: str
    - confidence: float
    - description: str
    - severity: str
    - sqi_quality: str
    - timestamp: str (optional)
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1e293b'),
        spaceAfter=20,
        alignment=1  # Center
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#64748b'),
        spaceAfter=10
    )
    
    elements = []
    
    # Header
    elements.append(Paragraph("CardioScan Analysis Report", title_style))
    elements.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    elements.append(Spacer(1, 20))
    
    # Summary Table
    severity_color = {
        'normal': colors.HexColor('#10b981'),  # Green
        'warning': colors.HexColor('#f59e0b'), # Amber
        'danger': colors.HexColor('#ef4444'),  # Red
        'caution': colors.HexColor('#f97316'), # Orange
        'unknown': colors.HexColor('#64748b')  # Slate
    }.get(data.get('severity', 'unknown'), colors.black)

    summary_data = [
        ['Parameter', 'Value'],
        ['Detected Condition', Paragraph(f"<b>{data.get('beat_type', 'N/A')}</b>", styles['Normal'])],
        ['Confidence Score', f"{data.get('confidence', 0)}%"],
        ['Severity Level', data.get('severity', 'Unknown').upper()],
        ['Signal Quality', data.get('sqi_quality', 'N/A')]
    ]
    
    t = Table(summary_data, colWidths=[2*inch, 4*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), colors.HexColor('#f1f5f9')),
        ('TEXTCOLOR', (0, 0), (1, 0), colors.HexColor('#334155')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#e2e8f0')),
        # Highlight severity row
        ('TEXTCOLOR', (1, 3), (1, 3), severity_color),
        ('FONTNAME', (1, 3), (1, 3), 'Helvetica-Bold'),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 20))
    
    # ECG Plot
    elements.append(Paragraph("Analyzed Signal Segment", subtitle_style))
    img_buffer = create_ecg_plot(data.get('signal', []))
    img = Image(img_buffer, width=6*inch, height=2.25*inch)
    elements.append(img)
    elements.append(Spacer(1, 20))

    # Detailed Findings
    elements.append(Paragraph("Clinical Interpretation", subtitle_style))
    description = data.get('description', 'No specific description available.')
    elements.append(Paragraph(description, styles['Normal']))
    elements.append(Spacer(1, 10))
    
    # Disclaimer
    elements.append(Spacer(1, 40))
    disclaimer_style = ParagraphStyle(
        'Disclaimer',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.HexColor('#94a3b8'),
        alignment=1
    )
    elements.append(Paragraph(
        "DISCLAIMER: This report is generated by an AI algorithm (CardioScan) and is for educational/research purposes only. "
        "It is NOT a medical diagnosis. Please create an appointment with a cardiologist for professional evaluation.",
        disclaimer_style
    ))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer
